baseURL = "https://souwest.ca/"
languageCode = "en-us"
theme = "airspace-hugo"
title = "Sou'West"
[[menu.footer]]
name = "Location"
url = "#feature"
weight = 4
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.footer]]
name = "Menu"
url = "#service"
weight = 3
[[menu.footer]]
name = "About Us"
url = "#intro"
weight = 2
[[menu.header]]
name = "About"
url = "#intro"
weight = 1
[[menu.header]]
name = "Location"
url = "#feature"
weight = 3
[[menu.header]]
name = "Menu"
url = "#service"
weight = 2
[params]
date_format = "2018-05-01T03:00:00+00:00"
home = "Home"
[params.blog]
enable = true
subtitle = "Catch up with us, anytime and anywhere"
title = "Get The Latest On What We're doing"
[params.call]
enable = false
paragraph = "- Randy M"
title = "\"As good as it gets on the North Shore\""