title = "Sou'West"
baseURL = "https://www.example.com"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "About"
    url = "#intro"
  [[menu.header]]
    weight = 3
    name = "Menu"
    url = "#service"
  [[menu.header]]
    weight = 4
    name = "Location"
    url = "#feature"

  [[menu.footer]]
    weight = 1
    name = "Home"
    url = "/"
  [[menu.footer]]
    weight = 2
    name = "About Us"
    url = "#intro"
  [[menu.footer]]
    weight = 3
    name = "Menu"
    url = "#service"
  [[menu.footer]]
    weight = 4
    name = "Location"
    url = "#feature"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 January 2006"

  home = "Home"

  [[params.photogallery]]
    img = "/souwest-port.jpg"
  [[params.photogallery]]
    img = "/souwest-port.jpg"
  [[params.photogallery]]
    img = "/souwest-port.jpg"

  [params.photofeed]
  instagramApiKey = "115568609"


  [params.slider]
    enable = true
    title = "Sou'West Bar & Grill"
    subtitle = ""

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics"
    paragraph = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id"

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Come visit us!"
    content = "6377a Prince Edward Island 20, Green Gables, PE C0A 1M0"
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    title = "\"As good as it gets on the North Shore\""
    paragraph = "- Randy M"

  [params.contactInfo]
    enable = true
    title = "Come visit us!"
    hours = "9-5 Monday - Friday<br/>9-7 Saturday - Sunday"
    phone = "(902) 315-2323"
    address = "6377a Prince Edward Island 20,<br/>Green Gables, PE C0A 1M0"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
