baseURL = "https://jamespohalloran.github.io/souwest/"
languageCode = "en-us"
theme = "airspace-hugo"
title = "Sou'West"
[[menu.footer]]
name = "About Us"
url = "#intro"
weight = 2
[[menu.footer]]
name = "Menu"
url = "#service"
weight = 3
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.footer]]
name = "Location"
url = "#feature"
weight = 4
[[menu.header]]
name = "Menu"
url = "#service"
weight = 2
[[menu.header]]
name = "Location"
url = "#feature"
weight = 3
[[menu.header]]
name = "About"
url = "#intro"
weight = 1
[params]
date_format = "2018-05-01T03:00:00+00:00"
home = "Home"
[params.blog]
enable = true
subtitle = "Catch up with us, anytime and anywhere"
title = "Get The Latest On What We're doing"
[params.gallery]
enable = true
title = "The Views"
[[params.gallery.images]]
alt = "sou west port"
img = "/images/souwest-port.jpg"
[[params.gallery.images]]
alt = "sou west sunny deck"
img = "/images/deck_day.jpg"
[[params.gallery.images]]
alt = "sou west evening deck"
img = "/images/deck_night.png"
[[params.gallery.images]]
alt = "sou west sunset"
img = "/images/deck_sunset.jpg"
[[params.gallery.images]]
alt = "sou west oysters pei"
img = "/images/oysters.jpg"
[[params.gallery.images]]
alt = "sou west port"
img = "/images/souwest-port.jpg"
[[params.gallery.images]]
alt = "sou west restaurant"
img = "/images/inner_souwest.jpg"
[[params.gallery.images]]
alt = "sou west deck"
img = "/images/deck.jpg"

[params.call]
enable = false
paragraph = "- Randy M"
title = "\"As good as it gets on the North Shore\""
[params.contact]
enable = true
subtitle = "Don’t just take our word for it. Check out some of our latest work."
title = "Drop us a note"
[params.contact.box]
address = "North Main Street, Brooklyn Australia"
email = "Email: contact@mail.com"
phone = "Phone: +88 01672 506 744"
title = "Stop by for a visit"
[params.contact.form]
button = "Send message"
email = "Your email"
message = "Your message"
name = "Your name"
subject = "Your subject"
[params.contact.gmaps]
title = "We Also Count in Google Maps"
[params.contactInfo]
address = "6377a Prince Edward Island 20,<br/>Green Gables, PE C0A 1M0"
enable = true
hours = "9-5 Monday - Friday<br/>9-7 Saturday - Sunday"
phone = "(902) 315-2323"
title = "Come visit us!"
[params.feature]
content = "6377a Prince Edward Island 20, Green Gables, PE C0A 1M0"
enable = true
title = "Come visit us!"
[params.feature.button]
caption = "View Works"
url = "#"
[params.photofeed]
instagramApiKey = "115568609"
[params.slider]
enable = true
subtitle = ""
title = ""
[params.wrapper]
enable = true
italic = ""
paragraph = "You could say there's salt water in our veins.<br>We love people, fish, shellfish and fishing. We love the sea.<br><br>The mussels, lobster, clams, oysters, and cherry stone quahogs that grow right in front of Sou'West are our pride and joy to serve you."
title = "About Us"
[[params.photogallery]]
img = "/souwest-port.jpg"
[[params.photogallery]]
img = "/souwest-port.jpg"
[[params.photogallery]]
img = "/souwest-port.jpg"
