baseURL = "https://www.example.com"
languageCode = "en-us"
theme = "airspace-hugo"
title = "Sou'West"
[[menu.footer]]
name = "Menu"
url = "#service"
weight = 3
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.footer]]
name = "About Us"
url = "#intro"
weight = 2
[[menu.footer]]
name = "Location"
url = "#feature"
weight = 4
[[menu.header]]
name = "About"
url = "#intro"
weight = 1
[[menu.header]]
name = "Menu"
url = "#service"
weight = 2
[[menu.header]]
name = "Location"
url = "#feature"
weight = 3
[params]
date_format = "6 January 2006"
home = "Home"
[params.blog]
enable = true
subtitle = "Catch up with us, anytime and anywhere"
title = "Get The Latest On What We're doing"
[params.call]
enable = false
paragraph = "- Randy M"
title = "\"As good as it gets on the North Shore\""
[params.contact]
enable = true
subtitle = "Don’t just take our word for it. Check out some of our latest work."
title = "Drop us a note"
[params.contact.box]
address = "North Main Street, Brooklyn Australia"
email = "Email: contact@mail.com"
phone = "Phone: +88 01672 506 744"
title = "Stop by for a visit"
[params.contact.form]
button = "Send message"
email = "Your email"
message = "Your message"
name = "Your name"
subject = "Your subject"
[params.contact.gmaps]
title = "We Also Count in Google Maps"
[params.contactInfo]
address = "6377a Prince Edward Island 20,<br/>Green Gables, PE C0A 1M0"
enable = true
hours = "9-5 Monday - Friday<br/>9-7 Saturday - Sunday"
phone = "(902) 315-2323"
title = "Come visit us!"
[params.feature]
content = "6377a Prince Edward Island 20, Green Gables, PE C0A 1M0"
enable = true
title = "Come visit us!"
[params.feature.button]
caption = "View Works"
url = "#"
[params.photofeed]
instagramApiKey = "115568609"
[params.slider]
enable = true
subtitle = ""
title = "Sou'West Bar & Grill"
[params.wrapper]
enable = true
italic = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics"
paragraph = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id"
title = "About Us"
[[params.photogallery]]
img = "/souwest-port.jpg"
[[params.photogallery]]
img = "/souwest-port.jpg"
[[params.photogallery]]
img = "/souwest-port.jpg"
