baseURL = "https://jamespohalloran.github.io/souwest/"
languageCode = "en-us"
theme = "airspace-hugo"
title = "Sou'West"
[[menu.footer]]
name = "Location"
url = "#feature"
weight = 4
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.footer]]
name = "Menu"
url = "#service"
weight = 3
[[menu.footer]]
name = "About Us"
url = "#intro"
weight = 2
[[menu.header]]
name = "About"
url = "#intro"
weight = 1
[[menu.header]]
name = "Location"
url = "#feature"
weight = 3
[[menu.header]]
name = "Menu"
url = "#service"
weight = 2
[params]
date_format = "2018-05-01T03:00:00+00:00"
home = "Home"
[params.blog]
enable = true
subtitle = "Catch up with us, anytime and anywhere"
title = "Get The Latest On What We're doing"
[params.call]
enable = false
paragraph = "- Randy M"
title = "\"As good as it gets on the North Shore\""
[params.contact]
enable = true
subtitle = "Don’t just take our word for it. Check out some of our latest work."
title = "Drop us a note"
[params.contact.box]
address = "North Main Street, Brooklyn Australia"
email = "Email: contact@mail.com"
phone = "Phone: +88 01672 506 744"
title = "Stop by for a visit"
[params.contact.form]
button = "Send message"
email = "Your email"
message = "Your message"
name = "Your name"
subject = "Your subject"
[params.contact.gmaps]
title = "We Also Count in Google Maps"
[params.contactInfo]
address = "6377 Route 20 New London Wharf,<br/>New London, Prince Edward Island, PE C0B 1MO"
enable = true
hours = "11am-10pm Monday - Friday<br/>8am-10pm Saturday - Sunday"
phone = "(902) 886-3000"
title = "Come visit us!"
[params.feature]
content = "6377 Route 20 New London Wharf,<br/>New London, PE, PE C0B 1MO"
enable = true
title = "Come visit us!"
[params.feature.button]
caption = "View Works"
url = "#"
[params.gallery]
enable = true
title = "The Views"
[[params.gallery.images]]
alt = "sou west port"
img = "/images/souwest-port.jpg"
[[params.gallery.images]]
alt = "sou west sunny deck"
img = "/images/deck_day.jpg"
[[params.gallery.images]]
alt = "sou west evening deck"
img = "/images/deck_night.png"
[[params.gallery.images]]
alt = "sou west sunset"
img = "/images/deck_sunset.jpg"
[[params.gallery.images]]
alt = "sou west oysters pei"
img = "/images/oysters.jpg"
[[params.gallery.images]]
alt = "sou west port"
img = "/images/souwest-port.jpg"
[[params.gallery.images]]
alt = "sou west restaurant"
img = "/images/inner_souwest.jpg"
[[params.gallery.images]]
alt = "sou west deck"
img = "/images/deck.jpg"
[params.photofeed]
instagramApiKey = "115568609"
[params.slider]
enable = true
subtitle = ""
title = ""
[params.wrapper]
enable = true
italic = ""
paragraph = "The waterfront view, the delicious cuisine and the local draft on tap are three of many reasons why Sou' West is a destination in the summer months for Islanders and visitors alike.<br/><br/>Sou' West Bar is located in New London, Prince Edward Island along the breathtaking waters of the New London Bay. One of Prince Edward Island's magnificent waterfront dining locations, Sou' West is sure to please seafood lovers and foodies alike!<br/><br/>Join us for a pint or a seafood dinner. We'll welcome you just the same!"
title = "About Us"
[[params.photogallery]]
img = "/souwest-port.jpg"
[[params.photogallery]]
img = "/souwest-port.jpg"
[[params.photogallery]]
img = "/souwest-port.jpg"
